services:
  # Base de datos MySQL (DESARROLLO - sin volumen persistente)
  mysql:
    image: mysql:8.0
    container_name: objetos_perdidos_mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: objetos_perdidos
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password123
    ports:
      - '3307:3306'
    volumes:
      # SIN volumen persistente - se recrea cada vez
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/migrate_2fa.sql:/docker-entrypoint-initdb.d/02-migrate_2fa.sql
    networks:
      - objetos_perdidos_network

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: objetos_perdidos_backend_dev
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: app_user
      DB_PASS: app_password123
      DB_NAME: objetos_perdidos
      JWT_SECRET: your_super_secret_jwt_key_here_2025
      REFRESH_TOKEN_SECRET: your_super_secret_refresh_key_here_2025
      RECAPTCHA_SECRET_KEY: 6LfyiYkrAAAAAPQbPiaZGH18T7UTDJQ6lrUynh3R
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src/uploads:/app/src/uploads
    depends_on:
      - mysql
    networks:
      - objetos_perdidos_network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:3000
        VITE_RECAPTCHA_SITE_KEY: 6LfyiYkrAAAAAFRUN69HasWGXUltHEEzWRJD1kHG
    container_name: objetos_perdidos_frontend_dev
    restart: always
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - objetos_perdidos_network

  # phpMyAdmin para administración de base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: objetos_perdidos_phpmyadmin_dev
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - objetos_perdidos_network

networks:
  objetos_perdidos_network:
    driver: bridge
# NO incluimos volúmenes persistentes para desarrollo
# Los datos se recrean cada vez que se levanta el proyecto
